### ISSUE TITLE
Browser testing checklist

### ISSUE THREAD

**Issue by ascott1** [cfpb/front-end#31]
Let's add a browser testing checklist with as a resource.

**Comment by anselmbradford** [comment]
From our 4/13 talk...
With guidelines for how/when to deprecate a supported legacy browser. What criteria means we no longer care about checking a browser before releasing to the public (note—this isn't saying a legacy browser shouldn't be checked, but when is it not a necessary check-off before release?).

**Comment by ascott1** [comment]
I think what you're describing is incredibly important @anselmbradford. Many sites are no longer supporting IE8 let alone IE7 for example... What's our threshold? And wow do we use analytics to be sure we're making informed decisions?

**Comment by anselmbradford** [comment]
RIP Internet Explorer Dev Center, 2000-2015 https://dev.windows.com/en-us/project-spartan-for-devs

**Comment by anselmbradford** [comment]
Per discussion with @virtix @rosskarchner @jimmynotjim @KimberlyMunoz @sebworks on 5/28, we discussed the value of normalizing browser support across bureau projects (though internal/external sites could differ in support) and dropping official support for IE7.

**Comment by Scotchester** [comment]
:+1: :100:

**Comment by cfarm** [comment]
from [OAH](https://github.cfpb.gov/OAH/OAH-notes/wiki/Browser-QA-Checklist/_edit)

Process
* [ ] quick call to get everyone together, assigned to browsers, timebox the testing
* [ ] prioritize issues in Github thread
* [ ] Log a bug with bookmarklet: [bookmark this link](https://github.cfpb.gov/OAH/OAH-notes/issues/new?body=%23%20URL%0D%0D%0D%23%20Actual%20Behavior%0D%0D%0D%23%20Expected%20Behavior%0D%0D%0D%23%20Steps%20to%20Reproduce%0D%0D%0D%23%20Screenshot&labels=bug)

Windows 7
* [ ] IE 11
* [ ] IE 10
* [ ] IE 9
* [ ] IE 8
* [ ] latest Chrome
* [ ] latest Firefox

Mac
* [ ] latest Chrome
* [ ] latest Firefox
* [ ] latest Safari

Mobile
* [ ] latest iPhone
* [ ] latest iPad
* [ ] latest Android
* [ ] latest BlackBerry

**Comment by anselmbradford** [comment]
See [GHE]/flapjack/Getting-started-with-Flapjack/issues/43 for FJ metrics

**Comment by ascott1** [comment]
This is in the repo. Closing!

**Comment by cfarm** [comment]
Reopening because this thread implies we dropped support for IE7 yet it is still on the checklist in the repo. Sup with that? (For the record, we are not supported IE7 on Owning a Home).

**Comment by ascott1** [comment]
Let's drop it from the checklist! I don't think any of our tools built over the last year or two support IE7. @cfarm, can you do the honors?

**Comment by KimberlyMunoz** [comment]
One other thing while this is open. I recently had a conversation with Bill and Audrey about what browsers visit CF.gov and what we should support. There's some recommendations here with exact numbers: [GHE]/flapjack/Getting-started-with-Flapjack/issues/43. 

The major thing that's missing is that we have a lot of folks accessing our website on older versions of Android and we should do a check to make sure the site works on those devices.

**Comment by Scotchester** [comment]
According to this weekend's browser version dashboard, it looks to me like Android 4.0 is at 1.5%, which is the threshold where we set it was okay to drop IE7 support. Other Android 4.x stock browsers add an inconsequential amount.

Should we drop our recommendation to test in Android 4.x stock browser?

**Comment by KimberlyMunoz** [comment]
I'd still push that we test it for a couple reasons.

1.) Folks who are on Android 4.0 have some really old phones and are probably among are most vulnerable consumers.

2.) Also, I went through and based these numbers on a 6-month time range so that minor fluctuations wouldn't affect it too much. I don't think the browsers we test should change on a month-by-month basis.

**Comment by Scotchester** [comment]
Agreed on number one.

As for two, I agree in principle, though in this case, like IE7, we know
that number is trending downward. The numbers of folks still using the
Android 4.x stock browser is not going to bounce back up any.

**Comment by KimberlyMunoz** [comment]
Let's address in a few months.
